
<?php

/**
 *
 * @description: APP Generated by phpHunter
 * @example: TestHandler Sample
 *
 */

class TestHandler
{
    private $attributeSample;

    /**
     * @constructor: TestHandler
    */
    public function __construct($attributeSample)
    {
        $this->attributeSample = $attributeSample;
    }

    /**
     * @methods: setTestHandler
     */
    public function setTestHandler()
    {
        //setters...
    }

    /**
     * @methods: getTestHandler
     */
    public function getTestHandler()
    {
        //getters...
    }

    /**
     * @methods: run
     */
    public function run()
    {
        //Run...
    }
}

?>

